###############################################################################
# Author: Ariel Skye Levy	 												  # 
# Date: 02-02-2016 															  #
#																			  #
# Project Euler 002															  #
#   Even Fibonacci Numbers													  # 
###############################################################################

'''
PROBLEM

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...abs
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

result = 2

old_fib = 1
new_fib = 2
cur_fib = 0
while (cur_fib < 4000000):
	cur_fib = old_fib + new_fib
	if (cur_fib%2 == 0):
		result += cur_fib
	old_fib = new_fib
	new_fib = cur_fib

print(result)
